remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-auto-image
#theme: jekyll-theme-hacker

title: [PawnMuncher's Munchies]
description: [musings of a cybersecurity consultant]

image: img/18076d61e83e49b8bc2ba26f1f55d1ad.png
thumb_img: "https://www.mjh3.com/img/18076d61e83e49b8bc2ba26f1f55d1ad.png"


