#remote_theme: pages-themes/hacker@v0.2.0
remote_theme: luxedo/jekyll-theme-potato-hacker
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-hacker

title: [PawnMuncher's Munchies]
description: [musings of a cybersecurity consultant]
