remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-hacker

title: [PawnMuncher's Munchies]
description: [musings of a cybersecurity consultant]

<head>
<meta property="og:image" content="https://www.mjh3.com/img/18076d61e83e49b8bc2ba26f1f55d1ad.png">
</head>

